"""User Table

Revision ID: 90c148f78235
Revises: 
Create Date: 2022-07-30 08:15:14.443723

"""
from xmlrpc.client import Boolean
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c148f78235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("username", sa.String(), nullable=False, unique=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default= sa.text('False') , nullable= False),
        sa.Column("super_user", sa.Boolean(), server_default= sa.text('False'), nullable= False),
        sa.Column("terms_of_service",  sa.Boolean(), server_default= sa.text('False'), nullable= False),        sa.Column("date_joined",sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,),
        sa.PrimaryKeyConstraint("id"),        
    )
      
    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    pass
    # ### end Alembic commands ###
